version: '3'
services:
  web:
    image: birnbaum/cc-backend:1.0.0
    ports:
      - "8000:80"
    volumes:
      - /etc:/hypervisor_etc
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname != cc-docker-fake-frontend
