version: '3'
services:
  cc-backend:
    image: birnbaum/cc-backend
    ports:
     - "80:8000"
    volumes:
     - type: volume
       source: /etc
       target: /hypervisor_etc
    deploy:
      replicas: 5
      restart_policy:
       - condition: on-failure
      placement:
       - constraints: node.hostname != cc-docker-frontend
